version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduquiz-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: eduquiz-web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: eduquiz-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: eduquiz
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: eduquiz_user
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: eduquiz-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata: